
CREATE TABLE LABOREOS
(
	LAB_CODIGO           INTEGER NOT NULL,
	LAB_PRECIO           INTEGER NULL,
	LAB_TIPO             VARCHAR(25) NULL,
	PRIMARY KEY (LAB_CODIGO)
);



CREATE UNIQUE INDEX XPKLABOREOS ON LABOREOS
(
	LAB_CODIGO
);



CREATE TABLE CAMPOS
(
	CAM_COD              INTEGER NOT NULL,
	CAM_NOMBRE           VARCHAR(18) NULL,
	CAM_HECTAREAS        INTEGER NULL,
	CAM_ALQUILADO        boolean NULL,
	PRIMARY KEY (CAM_COD)
);



CREATE UNIQUE INDEX XPKCAMPOS ON CAMPOS
(
	CAM_COD
);



CREATE TABLE LOTES
(
	LOT_COD              INTEGER NOT NULL,
	LOT_NUMERO           INTEGER NULL,
	LOT_CULTIVO          VARCHAR(25) NULL,
	LOT_HECTAREAS        INTEGER NULL,
	LOT_CAM_COD          INTEGER NULL,
	PRIMARY KEY (LOT_COD),
	FOREIGN KEY R_1 (LOT_CAM_COD) REFERENCES CAMPOS (CAM_COD)
);



CREATE UNIQUE INDEX XPKLOTES ON LOTES
(
	LOT_COD
);



CREATE INDEX XIF1LOTES ON LOTES
(
	LOT_CAM_COD
);



CREATE TABLE LABOREOS_LOTES
(
	LAB_CODIGO           INTEGER NOT NULL,
	LOT_COD              INTEGER NOT NULL,
	PRIMARY KEY (LAB_CODIGO,LOT_COD),
	FOREIGN KEY R_35 (LAB_CODIGO) REFERENCES LABOREOS (LAB_CODIGO),
	FOREIGN KEY R_36 (LOT_COD) REFERENCES LOTES (LOT_COD)
);



CREATE UNIQUE INDEX XPKLABOREOS_LOTES ON LABOREOS_LOTES
(
	LAB_CODIGO,
	LOT_COD
);



CREATE INDEX XIF1LABOREOS_LOTES ON LABOREOS_LOTES
(
	LAB_CODIGO
);



CREATE INDEX XIF2LABOREOS_LOTES ON LABOREOS_LOTES
(
	LOT_COD
);



CREATE TABLE PERSONAS
(
	PER_COD              INTEGER NOT NULL,
	PER_NOMBRE           VARCHAR(25) NULL,
	PER_APELLIDO         VARCHAR(25) NULL,
	PER_MAIL             VARCHAR(25) NULL,
	PER_DIRECCION        VARCHAR(25) NULL,
	PER_TELEFONO         VARCHAR(25) NULL,
	PER_DNI              VARCHAR(25) NULL,
	PRIMARY KEY (PER_COD)
);



CREATE UNIQUE INDEX XPKPERSONAS ON PERSONAS
(
	PER_COD
);



CREATE TABLE PERSONAS_LOTES
(
	PERS_LOT_COD         INTEGER NOT NULL,
	PER_LOTE_COD         INTEGER NOT NULL,
	PERS_LOTE_PAGO       CHAR(18) NULL,
	PRIMARY KEY (PERS_LOT_COD,PER_LOTE_COD),
	FOREIGN KEY R_32 (PERS_LOT_COD) REFERENCES PERSONAS (PER_COD),
	FOREIGN KEY R_33 (PER_LOTE_COD) REFERENCES LOTES (LOT_COD)
);



CREATE UNIQUE INDEX XPKPERSONAS_LOTES ON PERSONAS_LOTES
(
	PERS_LOT_COD,
	PER_LOTE_COD
);



CREATE INDEX XIF1PERSONAS_LOTES ON PERSONAS_LOTES
(
	PERS_LOT_COD
);



CREATE INDEX XIF2PERSONAS_LOTES ON PERSONAS_LOTES
(
	PER_LOTE_COD
);



CREATE TABLE MARCAS
(
	MAR_COD              INTEGER NOT NULL,
	MAR_NOMBRE           VARCHAR(25) NULL,
	MAR_TIPO             VARCHAR(25) NULL,
	PRIMARY KEY (MAR_COD)
);



CREATE UNIQUE INDEX XPKMARCAS ON MARCAS
(
	MAR_COD
);



CREATE TABLE AGROQUIMICOS
(
	AGR_COD              INTEGER NOT NULL,
	AGR_CANTIDAD         INTEGER NULL,
	AGR_TIPO             VARCHAR(18) NULL,
	AGR_PRECIO           INTEGER NULL,
	AGR_FECHACOMPRA      DATE NULL,
	AGR_MAR_COD          INTEGER NULL,
	PRIMARY KEY (AGR_COD),
	FOREIGN KEY R_5 (AGR_MAR_COD) REFERENCES MARCAS (MAR_COD)
);



CREATE UNIQUE INDEX XPKAGROQUIMICOS ON AGROQUIMICOS
(
	AGR_COD
);



CREATE INDEX XIF1AGROQUIMICOS ON AGROQUIMICOS
(
	AGR_MAR_COD
);



CREATE TABLE AGROQUIMICOS_LOTES
(
	AGROQ_LOT_COD        INTEGER NOT NULL,
	AGR_LOTE_COD         INTEGER NOT NULL,
	PRIMARY KEY (AGROQ_LOT_COD,AGR_LOTE_COD),
	FOREIGN KEY R_30 (AGROQ_LOT_COD) REFERENCES AGROQUIMICOS (AGR_COD),
	FOREIGN KEY R_31 (AGR_LOTE_COD) REFERENCES LOTES (LOT_COD)
);



CREATE UNIQUE INDEX XPKAGROQUIM_ICOS_LOTES ON AGROQUIMICOS_LOTES
(
	AGROQ_LOT_COD,
	AGR_LOTE_COD
);



CREATE INDEX XIF1AGROQUIM_ICOS_LOTES ON AGROQUIMICOS_LOTES
(
	AGROQ_LOT_COD
);



CREATE INDEX XIF2AGROQUIM_ICOS_LOTES ON AGROQUIMICOS_LOTES
(
	AGR_LOTE_COD
);



CREATE TABLE FERTILIZANTES
(
	FER_COD              INTEGER NOT NULL,
	FER_CANTIDAD         INTEGER NULL,
	FER_TIPO             VARCHAR(18) NULL,
	FER_PRECIO           INTEGER NULL,
	FER_FECHACOMPRA      DATETIME NULL,
	FER_MAR_COD          INTEGER NULL,
	PRIMARY KEY (FER_COD),
	FOREIGN KEY R_4 (FER_MAR_COD) REFERENCES MARCAS (MAR_COD)
);



CREATE UNIQUE INDEX XPKFERTILIZANTES ON FERTILIZANTES
(
	FER_COD
);



CREATE INDEX XIF1FERTILIZANTES ON FERTILIZANTES
(
	FER_MAR_COD
);



CREATE TABLE FERTILIZANTES_LOTES
(
	FERTI_LOT_COD        INTEGER NOT NULL,
	FER_LOTE_COD         INTEGER NOT NULL,
	PRIMARY KEY (FERTI_LOT_COD,FER_LOTE_COD),
	FOREIGN KEY R_28 (FERTI_LOT_COD) REFERENCES FERTILIZANTES (FER_COD),
	FOREIGN KEY R_29 (FER_LOTE_COD) REFERENCES LOTES (LOT_COD)
);



CREATE UNIQUE INDEX XPKFERTILIZANTES_LOTES ON FERTILIZANTES_LOTES
(
	FERTI_LOT_COD,
	FER_LOTE_COD
);



CREATE INDEX XIF1FERTILIZANTES_LOTES ON FERTILIZANTES_LOTES
(
	FERTI_LOT_COD
);



CREATE INDEX XIF2FERTILIZANTES_LOTES ON FERTILIZANTES_LOTES
(
	FER_LOTE_COD
);



CREATE TABLE SEMILLAS
(
	SEM_COD              INTEGER NOT NULL,
	SEM_CANTIDAD         INTEGER NULL,
	SEM_TIPO             VARCHAR(25) NULL,
	SEM_PRECIO           VARCHAR(25) NULL,
	SEM_FECHACOMPRA      DATETIME NULL,
	SEM_MAR_COD          INTEGER NULL,
	SEM_VARIEDAD         VARCHAR(25) NULL,
	PRIMARY KEY (SEM_COD),
	FOREIGN KEY R_2 (SEM_MAR_COD) REFERENCES MARCAS (MAR_COD)
);



CREATE UNIQUE INDEX XPKSEMILLAS ON SEMILLAS
(
	SEM_COD
);



CREATE INDEX XIF1SEMILLAS ON SEMILLAS
(
	SEM_MAR_COD
);



CREATE TABLE SEMILLAS_LOTES
(
	SEM_LOTE_COD         INTEGER NOT NULL,
	SEM_COD              INTEGER NOT NULL,
	PRIMARY KEY (SEM_LOTE_COD,SEM_COD),
	FOREIGN KEY R_27 (SEM_LOTE_COD) REFERENCES LOTES (LOT_COD),
	FOREIGN KEY R_34 (SEM_COD) REFERENCES SEMILLAS (SEM_COD)
);



CREATE UNIQUE INDEX XPKSEMILLAS_LOTES ON SEMILLAS_LOTES
(
	SEM_LOTE_COD,
	SEM_COD
);



CREATE INDEX XIF2SEMILLAS_LOTES ON SEMILLAS_LOTES
(
	SEM_LOTE_COD
);



CREATE INDEX XIF3SEMILLAS_LOTES ON SEMILLAS_LOTES
(
	SEM_COD
);



CREATE TABLE MAQUINARIAS
(
	MAQ_COD              INTEGER NOT NULL,
	MAQ_TIPO             VARCHAR(25) NULL,
	MAQ_MODELO           VARCHAR(25) NULL,
	MAQ_PRECIOCOMBUSTIBLE INTEGER NULL,
	MAQ_ALQUILADO        boolean NULL,
	MAQ_MAR_COD          INTEGER NULL,
	PRIMARY KEY (MAQ_COD),
	FOREIGN KEY R_3 (MAQ_MAR_COD) REFERENCES MARCAS (MAR_COD)
);



CREATE UNIQUE INDEX XPKMAQUINARIAS ON MAQUINARIAS
(
	MAQ_COD
);



CREATE INDEX XIF1MAQUINARIAS ON MAQUINARIAS
(
	MAQ_MAR_COD
);



CREATE TABLE MAQUINARIAS_LOTES
(
	MAQUI_LOT_COD        INTEGER NOT NULL,
	LOTE_MAQ_COD         INTEGER NOT NULL,
	PRIMARY KEY (MAQUI_LOT_COD,LOTE_MAQ_COD),
	FOREIGN KEY R_24 (MAQUI_LOT_COD) REFERENCES MAQUINARIAS (MAQ_COD),
	FOREIGN KEY R_25 (LOTE_MAQ_COD) REFERENCES LOTES (LOT_COD)
);



CREATE UNIQUE INDEX XPKMAQUINARIAS_LOTES ON MAQUINARIAS_LOTES
(
	MAQUI_LOT_COD,
	LOTE_MAQ_COD
);



CREATE INDEX XIF1MAQUINARIAS_LOTES ON MAQUINARIAS_LOTES
(
	MAQUI_LOT_COD
);



CREATE INDEX XIF2MAQUINARIAS_LOTES ON MAQUINARIAS_LOTES
(
	LOTE_MAQ_COD
);



CREATE TABLE USUARIOS
(
	USU_COD              INTEGER NOT NULL,
	USU_NOMBRE           VARCHAR(25) NULL,
	USU_PASS             VARCHAR(25) NULL,
	USU_PER_COD          INTEGER NULL,
	PRIMARY KEY (USU_COD),
	FOREIGN KEY R_10 (USU_PER_COD) REFERENCES PERSONAS (PER_COD)
);



CREATE UNIQUE INDEX XPKUSUARIOS ON USUARIOS
(
	USU_COD
);



CREATE INDEX XIF1USUARIOS ON USUARIOS
(
	USU_PER_COD
);



CREATE TABLE CAMPANIAS
(
	CAMPA_COD            INTEGER NOT NULL,
	CAMPA_NOMBRE         VARCHAR(25) NULL,
	PRIMARY KEY (CAMPA_COD)
);



CREATE UNIQUE INDEX XPKCAMPANIAS ON CAMPANIAS
(
	CAMPA_COD
);



CREATE TABLE CAMPANIAS_LOTES
(
	CAMPA_FECHAINICIO    CHAR(18) NULL,
	CAMPA_FECHACIERRE    CHAR(18) NULL,
	CAMPA_LOT_COD        INTEGER NOT NULL,
	CAMPA_COD            INTEGER NOT NULL,
	PRIMARY KEY (CAMPA_COD,CAMPA_LOT_COD),
	FOREIGN KEY R_20 (CAMPA_LOT_COD) REFERENCES LOTES (LOT_COD),
	FOREIGN KEY R_21 (CAMPA_COD) REFERENCES CAMPANIAS (CAMPA_COD)
);



CREATE UNIQUE INDEX XPKCAMPANIAS ON CAMPANIAS_LOTES
(
	CAMPA_COD,
	CAMPA_LOT_COD
);



CREATE INDEX XIF1CAMPANIAS ON CAMPANIAS_LOTES
(
	CAMPA_LOT_COD
);



CREATE INDEX XIF2CAMPANIAS ON CAMPANIAS_LOTES
(
	CAMPA_COD
);


